export const SPEAKERS = [
  { id: 564, name: 'Eleanor Pena', position: 'President of Sales', companyName: 'XYZ Company' },
  { id: 872, name: 'John Doe', position: 'Chief Executive Officer', companyName: 'ABC Corp' },
  {
    id: 345,
    name: 'Alice Smith',
    position: 'Vice President of Marketing',
    companyName: 'DEF Industries',
  },
  {
    id: 991,
    name: 'Michael Johnson',
    position: 'Chief Technology Officer',
    companyName: 'GHI Solutions',
  },
  { id: 734, name: 'Laura Kim', position: 'Director of Finance', companyName: 'JKL Enterprises' },
  { id: 456, name: 'David Lee', position: 'Product Manager', companyName: 'MNO Innovations' },
  {
    id: 129,
    name: 'Sophia Garcia',
    position: 'Human Resources Manager',
    companyName: 'PQR Holdings',
  },
  { id: 788, name: 'Daniel Evans', position: 'Operations Manager', companyName: 'STU Corp' },
  {
    id: 234,
    name: 'Emma Clark',
    position: 'Customer Success Manager',
    companyName: 'VWX Technologies',
  },
  { id: 567, name: 'James Turner', position: 'Sales Manager', companyName: 'YZT Global' },
  { id: 890, name: 'Olivia Harris', position: 'Marketing Coordinator', companyName: 'Alpha Group' },
  {
    id: 678,
    name: 'William Robinson',
    position: 'Chief Financial Officer',
    companyName: 'Beta Enterprises',
  },
  { id: 347, name: 'Mia Scott', position: 'IT Manager', companyName: 'Gamma Solutions' },
  { id: 236, name: 'Lucas Adams', position: 'Account Executive', companyName: 'Delta Innovations' },
  {
    id: 799,
    name: 'Grace Walker',
    position: 'Business Analyst',
    companyName: 'Epsilon Consulting',
  },
  { id: 459, name: 'Henry Martinez', position: 'Legal Counsel', companyName: 'Zeta Holdings' },
  { id: 576, name: 'Lily Lewis', position: 'Chief Operating Officer', companyName: 'Theta Corp' },
  { id: 231, name: 'Jacob King', position: 'Chief Marketing Officer', companyName: 'Iota Media' },
  {
    id: 876,
    name: 'Avery Green',
    position: 'Director of Engineering',
    companyName: 'Kappa Industries',
  },
  {
    id: 543,
    name: 'Amelia Young',
    position: 'Senior Software Engineer',
    companyName: 'Lambda Tech',
  },
  {
    id: 322,
    name: 'Benjamin Wright',
    position: 'Supply Chain Manager',
    companyName: 'Mu Logistics',
  },
  { id: 654, name: 'Evelyn Foster', position: 'Data Scientist', companyName: 'Nu Analytics' },
  {
    id: 797,
    name: 'Isaac Morgan',
    position: 'Business Development Manager',
    companyName: 'Xi Solutions',
  },
  { id: 237, name: 'Chloe Parker', position: 'UX Designer', companyName: 'Omicron Design' },
  { id: 123, name: 'Logan Ross', position: 'Cloud Architect', companyName: 'Pi Networks' },
];
